### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by bradleypeabody** [parallaxinc/PropWare#117]
Looks like an upgrade to david.zemon.name broke some documentation links.  E.g. https://raw.githubusercontent.com/parallaxinc/PropWare/develop/README.md has links like: http://david.zemon.name/PropWare/GettingStarted.xhtml which appears to have changed to: http://david.zemon.name/PropWare/#/getting-started

My suggestion would be to add redirects for the old Download and Getting Started URLs to 301 over to the new location (to handle any other possible external links as well).  Or possibly more expedient would be to just change the README.

**Comment by DavidZemon** [comment]
Thank you. Good point about the redirect - I'll get that going at least for the links listed in the README.

**Comment by DavidZemon** [comment]
I didn't bother redirecting every page individually... sorry. Sometimes I'm just lazy. But I did put a regex in there to redirect anything *.xhtml to the new homepage.

**Comment by bradleypeabody** [comment]
Gotcha, makes sense.  My main concern was that when I found a few broken links it looked to me initially like the project might have been dead.  Even if the links land on a page that isn't exactly what you wanted, as long as it's clear where the new documentation is, I'm sure it will be fine.  P.S. Thanks for fixing the download links (e.g. http://david.zemon.name:8111/repository/download/PPropWare_Develop/.lastSuccessful/PropWare-3.0.0.132-Generic-osx_cmake.zip?guest=1 -Ocmake.zip), I think I just had really bad timing and ran into the link issue above and then and also happened to also try downloading while the build system was having issues earlier today.

Everything looks great now though.

**Comment by DavidZemon** [comment]
Yea, bad day indeed. My server was migrated this weekend and a mistake was made during that migration, which is what brought down TeamCity (and therefore the download link) until the problem was brought to my attention a couple hours ago.

Btw, I notice you're looking at the osx package. There has been very limited testing of PropWare on Mac, so do please feel free to submit any new tickets here for help getting it setup. I have a label here on GitHub already setup for "questions" so its fine to report things here that are not bugs or feature requests.

**Comment by DavidZemon** [comment]
Well that didn't work out too well. I just broke the existing doxygen docs - they all redirect to the homepage now. Better come up with a different solution.

**Comment by avsa242** [comment]
@DavidZemon 
Not sure if this is because of the same issue, but none of the download links at the page referenced in the readme work:
https://david.zemon.name/PropWare/#/download

**Comment by DavidZemon** [comment]
Thanks for letting me know. The only thing I can figure out is that TeamCity must have changed the download URL for artifacts with the latest release. I'm getting it fixed now.

**Comment by DavidZemon** [comment]
Okay... working on getting this fixed. A few things all went wrong again. Most are fixed, but the links for the DEB and RPM packages are broken because they have been named incorrectly in the latest build. I'm working on getting that fixed. In the meantime, if you need the artifacts, please just download them directly from TeamCity: http://david.zemon.name:8111/viewLog.html?buildId=1791&buildTypeId=PropWare_Develop&tab=artifacts

**Comment by avsa242** [comment]
Awesome - quick turnaround, thanks!

**Comment by DavidZemon** [comment]
Okay, all download links now fixed.
